language: python
python:
  - "3.7"
sudo: false
install:
  - travis_wait source ./install_dependencies.sh
before_script:
  - pip install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov
